name: CI on Push and PullRequest

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    env:
      TZ: "Asia/Tokyo"
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Google Chrome for Frontend
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version
      - name: Setup Backend
        run: |
          cd backend
          npm install
          npm run prettier-ci
          npm run test
      - name: Setup Frontend
        run: |
          cd frontend
          PUPPETEER_SKIP_DOWNLOAD=true npm install
          npm run lint
          npm run prettier-ci
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          npm run build -- --configuration=production
